WORKOUT_TYPE_RUNNING = 1
WORKOUT_TYPE_CYCLING = 2
WORKOUT_TYPE_HIKING = 3

WORKOUT_TYPE_CHOICES = (
    (WORKOUT_TYPE_RUNNING, 'Running'),
    (WORKOUT_TYPE_CYCLING, 'Cycling'),
    (WORKOUT_TYPE_HIKING, 'Hiking'),
)
